-- CSH Atelier production upgrade 006
-- Fixes existing company-label catalogue image paths after local mirroring.
UPDATE products SET image_url='assets/img/catalog/mdlan-like-your-heart-joggers.jpg' WHERE slug='main-mdlan-like-your-heart-joggers' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-pure-mens-athletic-shoes.jpg' WHERE slug='main-mdlan-pure-mens-athletic-shoes' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-think-pixel-character-sherpa-blanket.jpg' WHERE slug='main-mdlan-think-pixel-character-sherpa-blanket' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-prioritize-your-well-being-pixel-art-cuffed-beanie.jpg' WHERE slug='main-mdlan-prioritize-your-well-being-pixel-art-cuffed-beanie' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-like-your-heart-cuffed-beanie.jpg' WHERE slug='main-mdlan-like-your-heart-cuffed-beanie' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-prioritize-your-well-being-unisex-hoodie.jpg' WHERE slug='main-mdlan-prioritize-your-well-being-unisex-hoodie' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-prioritize-your-well-being-pixel-heart-spiral-notebook.jpg' WHERE slug='main-mdlan-prioritize-your-well-being-pixel-heart-spiral-notebook' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-prioritize-your-well-being-pixel-geek-duffle-bag.jpg' WHERE slug='main-mdlan-prioritize-your-well-being-pixel-geek-duffle-bag' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-prioritize-your-well-being-socks.jpg' WHERE slug='main-mdlan-prioritize-your-well-being-socks' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-x-under-armour-prioritize-your-well-being-hat-2.jpg' WHERE slug='main-mdlan-x-under-armour-prioritize-your-well-being-hat-2' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-x-under-armour-prioritize-your-well-being-backpack.jpg' WHERE slug='main-mdlan-x-under-armour-prioritize-your-well-being-backpack' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-x-under-armour-prioritize-your-well-being-hat.jpg' WHERE slug='main-mdlan-x-under-armour-prioritize-your-well-being-hat' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-x-under-armour-womens-polo.jpg' WHERE slug='main-mdlan-x-under-armour-womens-polo' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-x-under-armour-prioritize-your-health-mens-polo.jpg' WHERE slug='main-mdlan-x-under-armour-prioritize-your-health-mens-polo' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-x-under-armour-prioritize-your-well-being-athletic-tee.jpg' WHERE slug='main-mdlan-x-under-armour-prioritize-your-well-being-athletic-tee' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-x-under-armour-athletic-tee.jpg' WHERE slug='main-mdlan-x-under-armour-athletic-tee' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-butterfly-manifesto-windbreaker-womens.jpg' WHERE slug='main-mdlan-butterfly-manifesto-windbreaker-womens' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-women-empowerment-water-bottle.jpg' WHERE slug='main-mdlan-women-empowerment-water-bottle' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-master-of-haute-wear-jacquard-knit-cardigan.jpg' WHERE slug='main-mdlan-master-of-haute-wear-jacquard-knit-cardigan' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/ur-art-0001-you-are-art.jpg' WHERE slug='main-ur-art-0001-you-are-art' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-women-empowerment-beanie.jpg' WHERE slug='main-mdlan-women-empowerment-beanie' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-noir-is-power-box-premier-t-shirt.jpg' WHERE slug='main-mdlan-noir-is-power-box-premier-t-shirt' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-women-empowerment-tracksuit.jpg' WHERE slug='main-mdlan-women-empowerment-tracksuit' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-gbv-awareness-kids-t-shirt.jpg' WHERE slug='main-mdlan-gbv-awareness-kids-t-shirt' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-women-empowerment-trucker-hat.jpg' WHERE slug='main-mdlan-women-empowerment-trucker-hat' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/mdlan-women-empowerment-jogger.jpg' WHERE slug='main-mdlan-women-empowerment-jogger' AND external_source="CSH Innovations Co.";
UPDATE products SET image_url='assets/img/catalog/csh-atelier-co-women-empowerment-tote-bags.jpg' WHERE slug='main-csh-atelier-co-women-empowerment-tote-bags' AND external_source="CSH Innovations Co.";
